"""initial schema

Revision ID: b5e999ce1e26
Revises: 
Create Date: 2026-10-07 00:40:42.764187
"""
from alembic import op
import sqlalchemy as sa

import app.core.encrypted_field


revision = 'b5e999ce1e26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_table('blocklist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('court_name', sa.String(length=200), nullable=True),
    sa.Column('conviction_date', sa.Date(), nullable=True),
    sa.Column('related_report_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_by', sa.String(length=36), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocklist_entries_phone_number'), 'blocklist_entries', ['phone_number'], unique=False)
    op.create_index(op.f('ix_blocklist_entries_sender_hash'), 'blocklist_entries', ['sender_hash'], unique=False)
    op.create_index(op.f('ix_blocklist_entries_source'), 'blocklist_entries', ['source'], unique=False)
    op.create_table('legal_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('court_number', sa.String(length=60), nullable=False),
    sa.Column('judge_name', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_ref', sa.String(length=36), nullable=True),
    sa.Column('related_report_id', sa.String(length=36), nullable=True),
    sa.Column('related_case_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_notes', sa.String(length=500), nullable=True),
    sa.Column('issued_by', sa.String(length=36), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_orders_order_number'), 'legal_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_legal_orders_order_type'), 'legal_orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_legal_orders_status'), 'legal_orders', ['status'], unique=False)
    op.create_index(op.f('ix_legal_orders_target_ref'), 'legal_orders', ['target_ref'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('governorate', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('primary_victim_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('victims_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_victim_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_assigned_to'), 'cases', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_priority'), 'cases', ['priority'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'consent_type', name='uq_user_consent_type')
    )
    op.create_index(op.f('ix_user_consents_consent_type'), 'user_consents', ['consent_type'], unique=False)
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('device_model', sa.String(length=120), nullable=True),
    sa.Column('os_version', sa.String(length=60), nullable=True),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device')
    )
    op.create_index(op.f('ix_user_devices_device_id'), 'user_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('victim_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('victim_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['victim_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_victim_notifications_created_at'), 'victim_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_victim_notifications_report_id'), 'victim_notifications', ['report_id'], unique=False)
    op.create_index(op.f('ix_victim_notifications_victim_id'), 'victim_notifications', ['victim_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('case_updates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_updates_case_id'), 'case_updates', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_updates_created_at'), 'case_updates', ['created_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('local_id', sa.String(length=36), nullable=False),
    sa.Column('report_number', sa.String(length=30), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('victim_id', sa.String(length=36), nullable=True),
    sa.Column('sender_raw', sa.String(length=160), nullable=False),
    sa.Column('sender_display', sa.String(length=160), nullable=False),
    sa.Column('sender_phone', app.core.encrypted_field.EncryptedString(length=120), nullable=True),
    sa.Column('sender_phone_hash', sa.String(length=64), nullable=True),
    sa.Column('sender_hash', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('source_app', sa.String(length=60), nullable=False),
    sa.Column('source_package', sa.String(length=60), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_reports_category'), 'reports', ['category'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_local_id'), 'reports', ['local_id'], unique=True)
    op.create_index(op.f('ix_reports_priority'), 'reports', ['priority'], unique=False)
    op.create_index(op.f('ix_reports_report_number'), 'reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_reports_risk_level'), 'reports', ['risk_level'], unique=False)
    op.create_index(op.f('ix_reports_sender_hash'), 'reports', ['sender_hash'], unique=False)
    op.create_index(op.f('ix_reports_sender_phone_hash'), 'reports', ['sender_phone_hash'], unique=False)
    op.create_index(op.f('ix_reports_source_app'), 'reports', ['source_app'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_victim_id'), 'reports', ['victim_id'], unique=False)
    op.create_table('blockchain_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=40), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('entries_count', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('anchored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anchored_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_anchors_batch_id'), 'blockchain_anchors', ['batch_id'], unique=True)
    op.create_index(op.f('ix_blockchain_anchors_report_id'), 'blockchain_anchors', ['report_id'], unique=False)
    op.create_table('cloud_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('legal_order_id', sa.String(length=36), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('files_count', sa.Integer(), nullable=False),
    sa.Column('files_list', sa.JSON(), nullable=True),
    sa.Column('submission_proof_path', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['legal_order_id'], ['legal_orders.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_orders_legal_order_id'), 'cloud_orders', ['legal_order_id'], unique=False)
    op.create_index(op.f('ix_cloud_orders_order_number'), 'cloud_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_cloud_orders_provider'), 'cloud_orders', ['provider'], unique=False)
    op.create_index(op.f('ix_cloud_orders_report_id'), 'cloud_orders', ['report_id'], unique=False)
    op.create_index(op.f('ix_cloud_orders_status'), 'cloud_orders', ['status'], unique=False)
    op.create_table('custody_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custody_entries_current_hash'), 'custody_entries', ['current_hash'], unique=False)
    op.create_index(op.f('ix_custody_entries_report_id'), 'custody_entries', ['report_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('encrypted_on_device', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_file_hash'), 'evidences', ['file_hash'], unique=False)
    op.create_index(op.f('ix_evidences_report_id'), 'evidences', ['report_id'], unique=False)
    op.create_table('forensic_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=30), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('device_type', sa.String(length=40), nullable=True),
    sa.Column('device_identifier', sa.String(length=120), nullable=True),
    sa.Column('seizure_location', sa.String(length=200), nullable=True),
    sa.Column('seizure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('officers', sa.String(length=300), nullable=True),
    sa.Column('imaging_tool', sa.String(length=60), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('extracted_files_count', sa.Integer(), nullable=True),
    sa.Column('extraction_notes', sa.String(length=500), nullable=True),
    sa.Column('erase_method', sa.String(length=60), nullable=True),
    sa.Column('erase_verification_hash', sa.String(length=64), nullable=True),
    sa.Column('erase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_cases_case_number'), 'forensic_cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_forensic_cases_report_id'), 'forensic_cases', ['report_id'], unique=False)
    op.create_index(op.f('ix_forensic_cases_status'), 'forensic_cases', ['status'], unique=False)
    op.create_table('international_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference_number', sa.String(length=30), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('target_country', sa.String(length=60), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_content', sa.Text(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_international_requests_reference_number'), 'international_requests', ['reference_number'], unique=True)
    op.create_index(op.f('ix_international_requests_report_id'), 'international_requests', ['report_id'], unique=False)
    op.create_index(op.f('ix_international_requests_request_type'), 'international_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_international_requests_status'), 'international_requests', ['status'], unique=False)
    op.create_table('perceptual_hashes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('watermark_payload', sa.JSON(), nullable=True),
    sa.Column('registered_by', sa.String(length=120), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perceptual_hashes_content_hash'), 'perceptual_hashes', ['content_hash'], unique=False)
    op.create_index(op.f('ix_perceptual_hashes_phash'), 'perceptual_hashes', ['phash'], unique=False)
    op.create_index(op.f('ix_perceptual_hashes_report_id'), 'perceptual_hashes', ['report_id'], unique=False)
    op.create_index(op.f('ix_perceptual_hashes_source'), 'perceptual_hashes', ['source'], unique=False)
    op.create_table('report_feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('victim_id', sa.String(length=36), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('extortion_kind', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_feedbacks_feedback_type'), 'report_feedbacks', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_report_feedbacks_report_id'), 'report_feedbacks', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_feedbacks_victim_id'), 'report_feedbacks', ['victim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_feedbacks_victim_id'), table_name='report_feedbacks')
    op.drop_index(op.f('ix_report_feedbacks_report_id'), table_name='report_feedbacks')
    op.drop_index(op.f('ix_report_feedbacks_feedback_type'), table_name='report_feedbacks')
    op.drop_table('report_feedbacks')
    op.drop_index(op.f('ix_perceptual_hashes_source'), table_name='perceptual_hashes')
    op.drop_index(op.f('ix_perceptual_hashes_report_id'), table_name='perceptual_hashes')
    op.drop_index(op.f('ix_perceptual_hashes_phash'), table_name='perceptual_hashes')
    op.drop_index(op.f('ix_perceptual_hashes_content_hash'), table_name='perceptual_hashes')
    op.drop_table('perceptual_hashes')
    op.drop_index(op.f('ix_international_requests_status'), table_name='international_requests')
    op.drop_index(op.f('ix_international_requests_request_type'), table_name='international_requests')
    op.drop_index(op.f('ix_international_requests_report_id'), table_name='international_requests')
    op.drop_index(op.f('ix_international_requests_reference_number'), table_name='international_requests')
    op.drop_table('international_requests')
    op.drop_index(op.f('ix_forensic_cases_status'), table_name='forensic_cases')
    op.drop_index(op.f('ix_forensic_cases_report_id'), table_name='forensic_cases')
    op.drop_index(op.f('ix_forensic_cases_case_number'), table_name='forensic_cases')
    op.drop_table('forensic_cases')
    op.drop_index(op.f('ix_evidences_report_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_file_hash'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_custody_entries_report_id'), table_name='custody_entries')
    op.drop_index(op.f('ix_custody_entries_current_hash'), table_name='custody_entries')
    op.drop_table('custody_entries')
    op.drop_index(op.f('ix_cloud_orders_status'), table_name='cloud_orders')
    op.drop_index(op.f('ix_cloud_orders_report_id'), table_name='cloud_orders')
    op.drop_index(op.f('ix_cloud_orders_provider'), table_name='cloud_orders')
    op.drop_index(op.f('ix_cloud_orders_order_number'), table_name='cloud_orders')
    op.drop_index(op.f('ix_cloud_orders_legal_order_id'), table_name='cloud_orders')
    op.drop_table('cloud_orders')
    op.drop_index(op.f('ix_blockchain_anchors_report_id'), table_name='blockchain_anchors')
    op.drop_index(op.f('ix_blockchain_anchors_batch_id'), table_name='blockchain_anchors')
    op.drop_table('blockchain_anchors')
    op.drop_index(op.f('ix_reports_victim_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_source_app'), table_name='reports')
    op.drop_index(op.f('ix_reports_sender_phone_hash'), table_name='reports')
    op.drop_index(op.f('ix_reports_sender_hash'), table_name='reports')
    op.drop_index(op.f('ix_reports_risk_level'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_number'), table_name='reports')
    op.drop_index(op.f('ix_reports_priority'), table_name='reports')
    op.drop_index(op.f('ix_reports_local_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_category'), table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_case_updates_created_at'), table_name='case_updates')
    op.drop_index(op.f('ix_case_updates_case_id'), table_name='case_updates')
    op.drop_table('case_updates')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_victim_notifications_victim_id'), table_name='victim_notifications')
    op.drop_index(op.f('ix_victim_notifications_report_id'), table_name='victim_notifications')
    op.drop_index(op.f('ix_victim_notifications_created_at'), table_name='victim_notifications')
    op.drop_table('victim_notifications')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_consent_type'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_priority'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_to'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_legal_orders_target_ref'), table_name='legal_orders')
    op.drop_index(op.f('ix_legal_orders_status'), table_name='legal_orders')
    op.drop_index(op.f('ix_legal_orders_order_type'), table_name='legal_orders')
    op.drop_index(op.f('ix_legal_orders_order_number'), table_name='legal_orders')
    op.drop_table('legal_orders')
    op.drop_index(op.f('ix_blocklist_entries_source'), table_name='blocklist_entries')
    op.drop_index(op.f('ix_blocklist_entries_sender_hash'), table_name='blocklist_entries')
    op.drop_index(op.f('ix_blocklist_entries_phone_number'), table_name='blocklist_entries')
    op.drop_table('blocklist_entries')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
